{{- if (.Capabilities.APIVersions.Has "kyverno.io/v1/ClusterPolicy") }}
{{- if .Values.policies.restrict_image_registries.enabled }}
---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: restrict-image-registries
  annotations:
    policies.kyverno.io/title: Restrict Image Registries
    policies.kyverno.io/category: SYS.1.6.A6
    policies.kyverno.io/severity: medium
    policies.kyverno.io/minversion: 1.6.0
    kyverno.io/kubernetes-version: "1.26"
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/description: >-
      No valid image registry. Use phoeni-docker-virtual.cluster.local or repo-ex.zcdi.dataport.de.
spec:
  validationFailureAction: {{ .Values.policies.restrict_image_registries.validationFailureAction | quote }}
  background: true
  rules:
  - name: validate-registries
    match:
      any:
      - resources:
          kinds:
          - Pod
    validate:
      message: "No valid image registry. Use phoeni-docker-virtual.cluster.local or repo-ex.zcdi.dataport.de."
      pattern:
        spec:
          =(ephemeralContainers):
            - image: "phoeni-docker-virtual.cluster.local/* | *.repo-ex.zcdi.dataport.de/*"
          =(initContainers):
            - image: "phoeni-docker-virtual.cluster.local/* | *.repo-ex.zcdi.dataport.de/*"
          containers:
            - image: "phoeni-docker-virtual.cluster.local/* | *.repo-ex.zcdi.dataport.de/*"
{{- end }}
{{- end }}
