---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: {{ .Values.ipPoolName }}-ipv4
  namespace: {{ .Release.Namespace }}
spec:
  addresses:
  {{- range .Values.address_ranges_ipv4 }}
    - {{ . }}
  {{- end }}

---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: {{ .Values.ipPoolName }}-ipv6
  namespace: metallb-system
spec:
  autoAssign: true
  addresses:
  {{- range .Values.address_ranges_ipv6 }}
  - {{ . }}
  {{- end }}
