---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: {{ .Values.ipPoolName }}
  namespace: metallb-system
spec:
  ipAddressPools:
    - {{ .Values.ipPoolName }}-ipv4
    - {{ .Values.ipPoolName }}-ipv6
