{{- if (.Capabilities.APIVersions.Has "kyverno.io/v1/ClusterPolicy") }}
---
apiVersion: kyverno.io/v2beta1
kind: PolicyException
metadata:
  name: managed-namespaces-skip-all
  namespace: {{ .Release.Namespace }}
  annotations:
    reason: >-
      We do not validate rules in the managed namespace.
spec:
  exceptions:
    - policyName: disallow-host-namespaces
      ruleNames:
        - "*"
    - policyName: disallow-host-path
      ruleNames:
        - "*"
    - policyName: disallow-host-ports
      ruleNames:
        - "*"
    - policyName: disallow-latest-tag
      ruleNames:
        - "*"
    - policyName: restrict-image-registries
      ruleNames:
        - "*"
  match:
    any:
      - resources:
          names:
            - "*"
          namespaces:
                  {{- range .Values.namespaces.managed }}
            - {{ . | quote }}
                  {{- end }}
{{- end }}
