---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: {{ .Values.ipPoolName }}
  namespace: {{ .Release.Namespace }}
spec:
  addresses:
  {{- range .Values.address_ranges }}
    - {{ . }}
  {{- end }}
